version: '3.9'
services:
  backendBoilerPslate:
    build: .
    container_name: backendBoilerPslate
    command: sh ./docker-entrypoint.sh
    restart: always
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      SERVER_PORT: $SERVER_PORT